language: android

env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
#    - sys-img-x86-android-17

#branches:
#    only:
#    - master

before_script:
    - chmod +x gradlew
    - chmod +x wait-for-emulator
    # add dummy git auth2 token
    - cp app/src/main/assets/tests/dummy_strings_private_app_pref.xml app/src/main/res/values/strings_private_app_pref.xml

    # Create and start emulator
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - adb wait-for-device
    - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTestFatDebug
# script: ./gradlew tasks
# androidTest