language: android
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/daemon"
  - "$HOME/.gradle/native"
  - "$HOME/.gradle/wrapper"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
sudo: false
branches:
  except:
  - master
env:
  global:
  - GRADLE_OPTS="-Xms128m"
  - secure: "roTPB93+Hvn2BRS9/ugRc7LuOKIxB3ok/7p29ZXc7HXVvDXHeUI9N6IR9Te5N/HJpX92xgSqv6Me0MQgsHKqJU8pyiEBbDx7b9wOPStFW7H8Pd8CE4PN3D9oC7OwLvKUBNMJ5ESLcpAG/ex4Hpd3eZNmaBUG+MbUgCljYI93p5v4+5BTWp410cjStObu13mAw1brkMNlimRAUBi8uGqAIvy9gwX/iJEZ3uPjoa6SIvBLclIueU6fRq0n2GzUCFEMChqdWrLeAyiaxE/UPtGAgsn+P4iBwQrPBkkK1wf8HH5HNOKHERDwCqRHFHNYAMqJ1gQ5wS19SNdJxSDuXGmbm5yjQMT6gHfpED0jlYcPEgVOJoQTX4/Vp+aWMoomw0ot1LCWoEe7My29AatJQDA4syB6JRVRtvDIzGwZnPNG0rKECClHS6rbxwbxCeMSnnjNVUQ+cE2W43yvEJlYuJMQw2yw6J8q2iCG6RwkbD3TPmgj0xKkqWTGGJYXQlgDcuAES/cpkyRDrxypHdbDXyD+XuJoMgFDtAjup47YMQCSh3xRCQ6xuvyEnU3c9hGMY8nf4J4iv6CHMKgVmH5mB4603+ampi/o3LbmYJiSKNofrlxNxWEQ5G0ribn0juBh8/A1WV0QCRQup6BAkeSd7/rDG7v3JTnoyC2aLJ/EaR3qMq4="
  - secure: "bjU4I8lqhOTwuJo18u6lM9XHyXac02eOTp9luVvui5h03ak4djdzbupkadvN6ZOnDBCDYV0PlYcRljibzfALCWXF/3maPZnm8oE5/hm7eKKdN9fPxrqWKCYfzGBUxsuQjPvJ6RtI/lQkneARP1YipAFw4u2UH+W+blDd9Y8TtQ6xjIfdBWhJC0BpdAq9AwuIriMiXu2aa5ouv5dOtzQFZZQk8TcsHYNfpQxgFIe1nz2NFQ9+BJCvMpn2tESzqvCix5vlj1oWkriZe8feh0jv/UhCleyG1Nivo3RNmaduKKfzRZ7ZVFpDk+zTRejHG7EJZyUi7QNGULbwTKQOypdCuSZTkA291jgdETobz0luKiqdXkQb90R66Wrym8ySLKn9bMPJLSSo7grtnHrT9vI6hZt73BF962ACrm+H0XcbA+whR23xyFg4A3N1EoH+XsTOzaOAS7XVaez2IkZVXQajdXCW7QSl+z5KkRwXDbsv4qEmwXzCEs2rCmsW+syM4ea+bC+7swE2XNHxH8H5GYgGbKeU8SHVPqzA06lM1zP286v+mfRcuKhPtFo/XNh/O925ps4TQXFh37opadLLPxvCO3xxKfOMvFcdRRF51cy7frqh7bMmytRpwsI38vmlGfnH1CFqU+jlZZEfKdYDAxcZatxdaC49LX1u0iGjK1n41gI="
  - secure: "VYSbTBrj2v5gxHfQ0L31QSDCDMam/osydDhps3/R0DZiD856XNfzULQKsWHHSqWgpa6gkIfpHAs6ynhPzLbI0poNydacJi6NTcZ4M5Kut4ZTY/ywTSTHrPOHtPCnLXGZbi8tOUmVOTccdohe3x0u4OAjwBRLZ9y4zkMGU+EUcyJ5JdPOwb6liJp+E8F+FNAD7VBgKekUozDslmkYPWcQ4h+GCr6f/entQjF+W6cBSC//JCWKgL/a2uUSRtZJsJ9Xxhw2P8aFC6ivEBE4N8D+baTlvZCtVV5KpzxhRbop/oiNZrqF4o0Z6zDkrau78VG41ktVIwkrsuPCCzuY3F2lO3TVl+IDjWp1s8t2vLFgkH7oGLv72FYmlY3p3lsUV4nKFe/wMvUUYv0FTvDmUWKAHjm3SeTJ1NQ2BWtVkluSu1DCqVdiddnKATuAdqQIT/E9SLD4qo9rte2YZVkxajn+0ZGEQHEkEzxKwgkSZN6kC+ZElzMUum4R0d4pRskFqj5iL+tEagP/cOGviL5Jj9J/Afy8qRGAAtLoi87FZa7fKPcK7xI0S5Qh9yTsHfJfVHHVeb7z7GY1sp6b8xSy3QxQ1Mw8HWU2KMuDeYkjZdifHh4kUVfQR9uQvvm0sANjP6y6M9sJdHTFXOoej5KBRMeAPpP3IVrjeztp0TEwLJb4z8U="
  - ARTIFACTS_PERMISSIONS=public-read
  matrix:
  - ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.1
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-android-19
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv strings_private_app_pref.xml app/src/main/res/values/strings_private_app_pref.xml
- wget --no-verbose -O containers.zip "https://btt-writer-resources.s3.amazonaws.com/containers.zip"
- if [ -f containers.zip ]; then rm ./app/src/main/assets/containers.zip && mv ./containers.zip ./app/src/main/assets/containers.zip; fi
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
before_script:
- chmod +x gradlew
script:
- ./gradlew test --stacktrace
- ./gradlew assembleRelease
- mv ./app/build/outputs/apk/release/release.apk ./app/build/outputs/apk/release/btt-writer.apk
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "wa-jenkins"
  - git config --local user.email "ci-cd@example.com"
  - export TRAVIS_TAG=${$(git describe --tags --abbrev=0)-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "s/Yy7CcMB0/BKbDg8r16fLBgUUJ8w6q+TC4KcXWsddjsVEl96/QH+aVQ3ViYsW0kI+khc6B0ejFJcMDleSSKsi5F9hQN2defS9mclMbpcJIydAQA+NYd3VH6ZMVtsNaM/eOIIURbG2AcuyB0jMTzRq3XGReUZeW4fXgGGy0Id/A2lKWJKRids4FaTs23Jc9HH7Zya8Kc8avZJmhw53Tycst1kb3YHQsb/njxPTXBiNBeNt2kdiQZpY/5VxVqR7NNZyND7m4DPL93xqIwO1fnYFcd8UOryyOqhXqoB8wNU/33/o4Vd0reeaFhPFiRk+1fxqpL87X2QDVodWJqaYyi8M3gdZYFJNsL797nTVxZ0lfphcjgZEBu+RXd7m9ze/nLPwYze/7//4veGqO0cn/PyxOE5Cvk1uJ8YASk5V/qULpISgNGvk8gm0/Qa6MdvfpnyOKTciTj992FGeNakt8OJcAIbe+FRG1ILLAcMQ5FSgAeG39aiCpK7PK4cgi6lO3XkLbTNIhyGl3v7Pt5pYctRXbanxCukI7Ma+LmdlfWZ5PzcMICnvVWnzixaI1HiHfo1cYe44cjmm/pZ6bWICEMy++B05wDyn/HKDMLamKf7r0TsNz6CwfK4G9wL1L9tFctjvQqgojhT+EZdR66kHsfP2ImExcrtTIYn1jZZCPMkpo="
  file: "./app/build/outputs/apk/release/btt-writer.apk"
  file_glob: true
  skip_cleanup: true
  on:
    repo: BTT-Writer-Android
    branch: master
addons:
  artifacts:
    s3_region: us-east-1
    target_paths:
    - "/BTT-Writer-Android/${TRAVIS_BUILD_NUMBER}/${TRAVIS_BRANCH}/${TRAVIS_TAG}"
    paths:
    - $(ls ./app/build/outputs/apk/release/btt-writer.apk | tr "\n" ":")
