[versions]
# Build Plugins
agp = "9.1.1"
kotlin = "2.2.21"
dexcount = "4.0.0"
composeBom = "2026.04.01"
decompose = "3.5.0"
kotlinxSerialization = "1.11.0"

# AndroidX Core
koin-bom = "4.2.1"
ktx = "1.18.0"
core-splashscreen = "1.2.0"
preference-ktx = "1.2.1"
documentfile = "1.1.0"

# Material Design
material = "1.13.0"

# Third-party Libraries
jgit = "5.13.5.202508271544-r"
jsch = "0.1.55"
itextg = "5.5.10"
gogs-client = "2.0.1"
resource-container = "1.0.0"
logger = "3.0.0"
foreground = "0.1.0"
firebase-appindexing = "20.0.0"
okhttp = "5.3.2"
markdownj = "0.4"
commons-io = "2.22.0"
ktor = "3.4.3"

# Testing
junit = "4.13.2"
junit-ext = "1.3.0"
hamcrest = "3.0"
test-runner = "1.7.0"
test-rules = "1.7.0"
uiautomator = "2.3.0"
orchestrator = "1.6.1"
mockk = "1.14.9"
mockwebserver = "5.3.2"
junit-jupiter = "6.0.3"
jsonVersion = "20251224"
kotlinx-coroutines-test = "1.10.2"

[libraries]
# AndroidX Core
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference-ktx" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }

# Material Design
json = { module = "org.json:json", version.ref = "jsonVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# Decompose
decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-extensions-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }

# Kotlinx Serialization
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Koin
koin-android = { module = "io.insert-koin:koin-android" }
koin-android-compat = { module = "io.insert-koin:koin-android-compat" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin-bom" }

# Git/SSH
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgit-ssh-jsch = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.ssh.jsch", version.ref = "jgit" }
jsch = { group = "com.jcraft", name = "jsch", version.ref = "jsch" }

# PDF
itextg = { group = "com.itextpdf", name = "itextg", version.ref = "itextg" }

# Bible Translation Tools
gogs-client = { group = "org.bibletranslationtools", name = "gogs-client", version.ref = "gogs-client" }
resource-container = { group = "org.bibletranslationtools", name = "resource-container", version.ref = "resource-container" }
bible-logger = { group = "org.bibletranslationtools", name = "logger", version.ref = "logger" }
foreground = { group = "org.unfoldingword.tools", name = "foreground", version.ref = "foreground" }

# Firebase
firebase-appindexing = { group = "com.google.firebase", name = "firebase-appindexing", version.ref = "firebase-appindexing" }

# Networking
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor"}
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }

# Markdown
markdownj = { group = "org.markdownj", name = "markdownj-core", version.ref = "markdownj" }

# Commons
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }

# Testing - JUnit
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junit-ext" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }

# Testing - Hamcrest
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }

# Testing - AndroidX Test
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "orchestrator" }

# Testing - MockK
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }

# Testing - Koin
koin-android-test = { group = "io.insert-koin", name = "koin-android-test", version.ref = "koin-bom" }

# Testing - kotlin coroutines
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dexcount = { id = "com.getkeepsafe.dexcount", version.ref = "dexcount" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
