package com.door43.translationstudio.ui.translate

import android.content.Context
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.view.View
import android.view.ViewGroup
import android.widget.SectionIndexer
import androidx.recyclerview.widget.RecyclerView
import com.door43.data.AssetsProvider
import com.door43.translationstudio.core.TranslationViewMode
import com.door43.translationstudio.core.Typography
import com.door43.translationstudio.rendering.RenderingProvider
import com.door43.translationstudio.ui.translate.review.SearchSubject

/**
 * Created by joel on 9/18/2015.
 */
abstract class ViewModeAdapter<VH : RecyclerView.ViewHolder> : RecyclerView.Adapter<VH>(), SectionIndexer {

    private val viewHolders = mutableListOf<VH>()

    open var onClickListener: OnEventListener? = null

    /**
     * The position where the list should start when first built
     */
    open var startPosition = 0

    private var currentPosition = -1
    private var currentMovementDirection = MovementDirection.UNKNOWN

    var showMergeSummary = false
    protected var layoutBuildNumber = 0
    protected lateinit var context: Context
    protected lateinit var typography: Typography
    protected lateinit var renderingProvider: RenderingProvider
    protected lateinit var assetsProvider: AssetsProvider

    protected val items = mutableListOf<ListItem>()
    val filteredItems = mutableListOf<ListItem>()
    protected val chapters = mutableListOf<String>()
    protected val filteredChapters = mutableListOf<String>()

    private enum class MovementDirection {
        UP,
        DOWN,
        UNKNOWN
    }

    /**
     * Returns the ViewHolder generated by the child class so we can keep track of it
     */
    abstract fun onCreateManagedViewHolder(parent: ViewGroup, viewType: Int): VH

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): VH {
        val holder = onCreateManagedViewHolder(parent, viewType)
        viewHolders.add(holder)
        return holder
    }

    /**
     * Binds the ViewHolder to the current position
     */
    abstract fun onBindManagedViewHolder(holder: VH, position: Int)

    override fun onBindViewHolder(holder: VH, position: Int) {
        onBindManagedViewHolder(holder, position)
        val range = calculateVisibleItems(position)
        onVisiblePositionsChanged(range)
    }

    override fun onAttachedToRecyclerView(recyclerView: RecyclerView) {
        super.onAttachedToRecyclerView(recyclerView)
        context = recyclerView.context
    }

    /**
     * Calculates a theoretical range of visible positions.
     * You should validate the upper bound.
     *
     * @param nextPosition the next position visited in the list
     * @return the range of visible positions.
     */
    private fun calculateVisibleItems(nextPosition: Int): IntArray {
        var max = 0
        var min = 0
        when (currentMovementDirection) {
            MovementDirection.DOWN -> {
                if (nextPosition >= this.currentPosition) {
                    // continue direction
                    max = nextPosition
                    min = nextPosition - (viewHolders.size - 1)
                } else {
                    // reverse
                    max = nextPosition + viewHolders.size - 1
                    min = nextPosition
                    currentMovementDirection = MovementDirection.UP
                }
            }
            MovementDirection.UP -> {
                if (nextPosition <= this.currentPosition) {
                    // continue direction
                    max = nextPosition + viewHolders.size - 1
                    min = nextPosition
                } else {
                    // reverse
                    max = nextPosition
                    min = nextPosition - (viewHolders.size - 1)
                    currentMovementDirection = MovementDirection.DOWN
                }
            }
            MovementDirection.UNKNOWN -> {
                max = nextPosition + viewHolders.size - 1
                min = nextPosition - (viewHolders.size - 1)
            }
        }

        // constrain bounds
        if (min < 0) {
            max -= min // TRICKY: -- = +
            min = 0
        }

        return intArrayOf(min, max)
    }

    /**
     * Called when the range of visible positions has changed.
     * You should validate the upper bound.
     *
     * @param range the theoretical range of visible positions.
     */
    protected open fun onVisiblePositionsChanged(range: IntArray) {
        // stub
    }

    open fun updateListStartPosition(startPosition: Int) {
        this.startPosition = startPosition
    }

    /**
     * get the chapter slug for the position
     */
    fun getChapterSlug(position: Int): String {
        val section = getSectionForPosition(position)
        val sectionsArray = sections
        if (sectionsArray != null && section >= 0 && section < sectionsArray.size) {
            return sectionsArray[section] as? String ?: ""
        }
        return ""
    }

    /**
     * Sets the resources opened status
     */
    abstract fun setResourcesOpened(status: Boolean)

    /**
     * calls notify dataset changed and triggers some other actions
     */
    @Suppress("NotifyDataSetChanged")
    fun triggerNotifyDataSetChanged() {
        notifyDataSetChanged()
        onClickListener?.onDataSetChanged(itemCount)
    }

    protected fun triggerNotifyItemChanged(position: Int) {
        notifyItemChanged(position)
        onClickListener?.onDataSetChanged(1)
    }

    protected fun triggerNotifyItemChanged(item: ListItem) {
        notifyItemChanged(filteredItems.indexOf(item))
        onClickListener?.onDataSetChanged(1)
    }

    /**
     * Filters the adapter by the constraint
     * @param constraint the search query
     * @param subject the text that will be searched
     */
    open fun filter(constraint: CharSequence?, subject: SearchSubject?, initialPosition: Int) {
        // Override this in your adapter to enable searching
    }

    /**
     * move to next/previous search item
     * @param next if true then find next, otherwise will find previous
     */
    open fun onMoveSearch(next: Boolean) {
        // Override this in your adapter to enable next/previous
    }

    /**
     * Update the list of items
     */
    open fun initializeListItems(
        listItems: List<ListItem>,
        startingChapter: String,
        startingChunk: String
    ) {
        layoutBuildNumber++ // force resetting of fonts
        items.clear()
        chapters.clear()
        filteredItems.clear()
        filteredChapters.clear()

        var foundPosition = false
        for (item in listItems) {
            if (!foundPosition && item.chapterSlug == startingChapter && item.chunkSlug == startingChunk) {
                startPosition = items.size
                foundPosition = true
            }
            if (!chapters.contains(item.chapterSlug)) {
                chapters.add(item.chapterSlug)
            }
            items.add(createListItem(item))
        }

        filteredChapters.addAll(chapters)
        filteredItems.addAll(items)
    }

    /**
     * need to override
     */
    abstract fun createListItem(item: ListItem): ListItem

    abstract fun markAllChunksDone()

    /**
     * check all cards for merge conflicts to see if we should show warning.
     */
    protected open fun doCheckForMergeConflict() {
        val hasConflicts = conflictsCount > 0
        val hand = Handler(Looper.getMainLooper())
        hand.post {
            onClickListener?.onEnableMergeConflict(hasConflicts, false)
        }
    }

    /**
     * Checks if filtering is enabled for this adapter.
     * Override this to customize filtering.
     * @return true if filtering is enabled
     */
    open fun hasFilter(): Boolean {
        return false
    }

    /**
     * returns the frame at the given position
     */
    abstract fun getFocusedChunkSlug(position: Int): String

    /**
     * returns the frame at the given position
     */
    abstract fun getFocusedChapterSlug(position: Int): String

    /**
     * Returns the position of an item in the adapter.
     * @return -1 if no item is found
     */
    open fun getItemPosition(chapterSlug: String, chunkSlug: String): Int {
        val item = getItem(chapterSlug, chunkSlug)
        return filteredItems.indexOf(item)
    }

    protected open fun getItem(chapterSlug: String, chunkSlug: String): ListItem? {
        for (item in filteredItems) {
            if (item.isChunk && chapterSlug == item.chapterSlug && chunkSlug == item.chunkSlug) {
                return item
            }
        }
        return null
    }

    protected open fun getItem(position: Int): ListItem? {
        if (position in 0 until filteredItems.size) {
            return filteredItems[position]
        }
        return null
    }

    /**
     * Restarts the auto commit timer
     */
    fun restartAutoCommitTimer() {
        onClickListener?.restartAutoCommitTimer()
    }

    /**
     * called to set new selected position
     * @param offset - if greater than or equal to 0, then set specific offset
     */
    protected fun onSetSelectedPosition(position: Int, offset: Int) {
        onClickListener?.onSetSelectedPosition(position, offset)
    }

    /**
     * returns true if merge conflict summary dialog is being displayed. Override in adapters that
     * support this.
     */
    open fun isMergeConflictSummaryDisplayed(): Boolean {
        return false
    }

    /**
     * enable/disable merge conflict filter in adapter
     * @param forceMergeConflict - if true, then will initialize have merge conflict flag to true
     */
    protected open fun setMergeConflictFilter(enableFilter: Boolean, forceMergeConflict: Boolean) {
        // Override this in your adapter to enable merge conflict filtering
    }

    protected open val conflictsCount: Int
        get() = items.count { it.hasMergeConflicts }

    interface OnEventListener : OnViewModeListener {
        fun showKeyboard(view: View)
        fun closeKeyboard()
        fun openTranslationMode(mode: TranslationViewMode, extras: Bundle?)
        fun onTranslationWordClick(resourceContainerSlug: String, chapterSlug: String, width: Int)
        fun onTranslationManualClick(section: String, slug: String)
        fun onTranslationNoteClick(note: TranslationHelp, width: Int)
        fun onTranslationQuestionClick(question: TranslationHelp, width: Int)
        fun scrollToChunk(chapterSlug: String, frameSlug: String)
        fun restartAutoCommitTimer()
        fun onSearching(enable: Boolean, foundCount: Int, atEnd: Boolean, atStart: Boolean)
        fun onDataSetChanged(count: Int)
        fun onEnableMergeConflict(showConflicted: Boolean, active: Boolean)
        fun onSetSelectedPosition(position: Int, offset: Int)
        fun getVisibleViewHolder(position: Int): RecyclerView.ViewHolder?
    }
}