package com.door43.translationstudio.rendering

import android.content.Context
import android.graphics.Typeface
import android.text.Layout
import android.text.Spannable
import android.text.SpannableString
import android.text.SpannableStringBuilder
import android.text.TextUtils
import android.text.style.AlignmentSpan
import android.text.style.BackgroundColorSpan
import android.text.style.StyleSpan
import android.util.Pair
import com.door43.translationstudio.ui.spannables.Span
import com.door43.translationstudio.ui.spannables.USXChar
import com.door43.translationstudio.ui.spannables.USXNoteSpan
import com.door43.translationstudio.ui.spannables.USXVersePinSpan
import com.door43.translationstudio.ui.spannables.USXVerseSpan
import java.util.regex.Pattern

/**
 * This is the USX rendering engine. This handles all of the rendering for USX formatted source and translation
 * NOTE: when rendering large chunks of text it is important to always keep things as a CharSequence and not string
 * so that spans generated by prior rendering methods are not lost.
 */
class USXRenderer : ClickableRenderingEngine {

    private var noteListener: Span.OnClickListener? = null
    private var verseListener: Span.OnClickListener? = null
    private var renderLineBreaks = false
    private var renderParagraphs = true
    private var renderVerses = true
    private var search: String? = null
    private var highlightColor = 0
    private var expectedVerseRange = IntArray(0)
    private var suppressLeadingMajorSectionHeadings = false
    private var addedMissingVerse = false

    /**
     * Creates a new usx rendering engine without any listeners
     */
    constructor(context: Context) {
        this.context = context
    }

    /**
     * Creates a new usx rendering engine with some custom click listeners
     * @param verseListener
     */
    constructor(
        context: Context,
        verseListener: Span.OnClickListener?,
        noteListener: Span.OnClickListener?
    ) {
        this.context = context
        this.verseListener = verseListener
        this.noteListener = noteListener
    }

    /**
     * if set to false verses will not be displayed in the output.
     *
     * @param enable default is true
     */
    override fun setVersesEnabled(enable: Boolean) {
        renderVerses = enable
    }

    /**
     * if set to true, then paragraphs (\p) will be rendered in the output.
     *
     * @param enable default is true
     */
    override fun setParagraphsEnabled(enable: Boolean) {
        renderParagraphs = enable
    }

    /**
     * If set to not null matched strings will be highlighted.
     *
     * @param searchString - null is disable
     * @param highlightColor
     */
    override fun setSearchString(searchString: CharSequence, highlightColor: Int) {
        this.highlightColor = highlightColor
        search = if (searchString.isNotEmpty()) {
            searchString.toString().lowercase()
        } else {
            null
        }
    }

    /**
     * Specifies an inclusive range of verses expected in the input.
     * If a verse is not found it will be inserted at the front of the input.
     * @param verseRange
     */
    override fun setPopulateVerseMarkers(verseRange: IntArray) {
        expectedVerseRange = verseRange
    }

    /**
     * Set whether to suppress display of major section headers.
     *
     * <p>The intent behind this is that major section headers prior to chapter markers will be
     * displayed above chapter markers, but only in read mode.</p>
     *
     * @param suppressLeadingMajorSectionHeadings The value to set
     */
    override fun setSuppressLeadingMajorSectionHeadings(suppressLeadingMajorSectionHeadings: Boolean) {
        this.suppressLeadingMajorSectionHeadings = suppressLeadingMajorSectionHeadings
    }

    /**
     * Renders the usx input into a readable form
     * @param input the raw input string
     * @return
     */
    override fun render(input: CharSequence): CharSequence {
        var out = input

        out = trimWhitespace(out)
        if (isStopped()) return input
        if (!renderLineBreaks) {
            out = renderLineBreaks(out)  // TODO: Eventually we may want to convert these to paragraphs.
            if (isStopped()) return input
        }
//        out = renderWhiteSpace(out)
        out = renderMajorSectionHeading(out)
        if (isStopped()) return input
        out = renderSectionHeading(out)
        if (isStopped()) return input
        out = renderParagraph(out)
        if (isStopped()) return input
        out = renderBlankLine(out)
        if (isStopped()) return input
        out = renderPoeticLine(out)
        if (isStopped()) return input
        out = renderRightAlignedPoeticLine(out)
        if (isStopped()) return input
        out = renderVerse(out)
        if (isStopped()) return input
        out = renderHighlightSearch(out)
        if (isStopped()) return input
        out = renderNote(out)
        if (isStopped()) return input
        out = renderChapterLabel(out)
        if (isStopped()) return input
        out = renderSelah(out)
        if (isStopped()) return input
        out = renderBrokenMarkers(out)
        if (isStopped()) return input
        out = renderCharTags(out)
        if (isStopped()) return input

        return out
    }

    /**
     * Renders all the Selah tags
     * @param input
     * @return
     */
    private fun renderSelah(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = USXChar.getPattern(USXChar.STYLE_SELAH)
        val matcher = pattern.matcher(input)
        var lastIndex = 0
        while (matcher.find()) {
            if (isStopped()) return input
            val span = SpannableStringBuilder(matcher.group(1))
            span.setSpan(StyleSpan(Typeface.ITALIC), 0, span.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
            span.setSpan(AlignmentSpan.Standard(Layout.Alignment.ALIGN_OPPOSITE), 0, span.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
            out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), "\n", span)
            lastIndex = matcher.end()
        }
        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Strips out new lines and replaces them with a single space
     * @param input
     * @return
     */
    fun trimWhitespace(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = Pattern.compile("(^\\s*|\\s*$)")
        val matcher = pattern.matcher(input)
        var lastIndex = 0
        while (matcher.find()) {
            if (isStopped()) return input
            out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), "")
            lastIndex = matcher.end()
        }
        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Renders section headings.
     * @param input
     * @return
     */
    fun renderSectionHeading(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = paraPattern("s")
        val matcher = pattern.matcher(input)
        var lastIndex = 0

        while (matcher.find()) {
            if (isStopped()) return input
            val span = SpannableStringBuilder(matcher.group(1))
            span.setSpan(StyleSpan(Typeface.BOLD), 0, span.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
            span.setSpan(AlignmentSpan.Standard(Layout.Alignment.ALIGN_CENTER), 0, span.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
            out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), span, "\n")
            lastIndex = matcher.end()
        }

        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Renders highlights search string.
     * @param input
     * @return
     */
    fun renderHighlightSearch(input: CharSequence): CharSequence {
        if (search == null) {
            return input
        }

        var out: CharSequence = ""
        val lowerCaseText = input.toString().lowercase()
        var lastIndex = 0

        while (lastIndex < input.length) {
            if (isStopped()) return input

            val pos = lowerCaseText.indexOf(search!!, lastIndex)
            if (pos < 0) {
                break
            }

            val span = SpannableStringBuilder(input.subSequence(pos, pos + search!!.length))
            span.setSpan(BackgroundColorSpan(highlightColor), 0, span.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)

            out = TextUtils.concat(out, input.subSequence(lastIndex, pos), span)

            lastIndex = pos + search!!.length
        }

        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Renders major section headings.
     * @param input
     * @return
     */
    fun renderMajorSectionHeading(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = paraPattern("ms")
        val matcher = pattern.matcher(input)
        var lastIndex = 0

        while (matcher.find()) {
            if (isStopped()) return input

            if (suppressLeadingMajorSectionHeadings && 0 == matcher.start()) {
                out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()))
            } else {
                val span = SpannableStringBuilder(matcher.group(1)!!.uppercase())
                span.setSpan(StyleSpan(Typeface.BOLD), 0, span.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
                span.setSpan(AlignmentSpan.Standard(Layout.Alignment.ALIGN_CENTER), 0, span.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
                out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), span, "\n")
            }
            lastIndex = matcher.end()
        }

        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Strips out extra whitespace from the text
     * @param input
     * @return
     */
    fun renderWhiteSpace(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = Pattern.compile("(\\s+)")
        val matcher = pattern.matcher(input)
        var lastIndex = 0
        while (matcher.find()) {
            if (isStopped()) return input
            out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), " ")
            lastIndex = matcher.end()
        }
        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Strips out new lines and replaces them with a single space
     * @param input
     * @return
     */
    fun renderLineBreaks(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = Pattern.compile("(\\s*\\n+\\s*)")
        val matcher = pattern.matcher(input)
        var lastIndex = 0
        while (matcher.find()) {
            if (isStopped()) return input
            out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), " ")
            lastIndex = matcher.end()
        }
        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Renders all note tags
     * @param input
     * @return
     */
    fun renderNote(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = Pattern.compile(USXNoteSpan.PATTERN)
        val matcher = pattern.matcher(input)
        var lastIndex = 0
        while (matcher.find()) {
            if (isStopped()) return input
            val noteText = matcher.group()
            val note = USXNoteSpan.parseNote(noteText)
            if (note != null) {
                note.onClickListener = noteListener
                if (search != null) {
                    val foundSearch = noteText.lowercase().contains(search!!)
                    note.isHighlight = foundSearch
                }
                out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), note.toCharSequence(context))
            } else {
                // failed to parse the note
                out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.end()))
            }

            lastIndex = matcher.end()
        }
        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Renders all verse tags
     * @param input
     * @return
     */
    override fun renderVerse(input: CharSequence): CharSequence {
        addedMissingVerse = false
        var out: CharSequence = ""

        val insert: CharSequence = ""

        val pattern = Pattern.compile(USXVerseSpan.PATTERN)
        val matcher = pattern.matcher(input)
        var lastIndex = 0
        val foundVerses = ArrayList<Int>()
        while (matcher.find()) {
            if (isStopped()) return input
            if (renderVerses) {
                val verse: Span
                if (verseListener == null) {
                    verse = USXVerseSpan(matcher.group(1))
                } else {
                    verse = USXVersePinSpan(matcher.group(1))
                }

                // record found verses
                val startVerse = (verse as USXVerseSpan).startVerseNumber
                var endVerse = verse.endVerseNumber
                var alreadyRendered = false
                if (endVerse > startVerse) {
                    // range of verses
                    for (i in startVerse..endVerse) {
                        if (!foundVerses.contains(i)) {
                            foundVerses.add(i)
                        } else {
                            alreadyRendered = true
                        }
                    }
                } else {
                    if (!foundVerses.contains(startVerse)) {
                        foundVerses.add(startVerse)
                    } else {
                        alreadyRendered = true
                    }
                }
                // render verses not already found
                if (!alreadyRendered) {
                    // exclude verses not within the range
                    var invalidVerse = false
                    if (expectedVerseRange.isNotEmpty()) {
                        val minVerse = expectedVerseRange[0]
                        var maxVerse = if (expectedVerseRange.size > 1) expectedVerseRange[1] else 0
                        if (maxVerse == 0) maxVerse = minVerse

                        val verseNumStart = verse.startVerseNumber
                        var verseNumEnd = verse.endVerseNumber
                        if (verseNumEnd == 0) verseNumEnd = verseNumStart
                        invalidVerse = verseNumStart !in minVerse..maxVerse || verseNumEnd < minVerse || verseNumEnd > maxVerse
                    }
                    if (!invalidVerse) {
                        verse.onClickListener = verseListener
                        out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), insert, verse.toCharSequence(context))
                    } else {
                        // exclude invalid verse
                        out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()))
                    }
                } else {
                    // exclude duplicate verse
                    out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()))
                }
            } else {
                // exclude verse from display
                out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()))
            }
            lastIndex = matcher.end()
        }
        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))

        if (renderVerses) {
            // populate missing verses
            if (expectedVerseRange.size == 1) {
                if (!foundVerses.contains(expectedVerseRange[0])) {
                    // generate missing verse
                    val verse: Span
                    if (verseListener == null) {
                        verse = USXVerseSpan(expectedVerseRange[0])
                    } else {
                        verse = USXVersePinSpan(expectedVerseRange[0])
                    }
                    verse.onClickListener = verseListener
                    out = TextUtils.concat(verse.toCharSequence(context), out)
                    addedMissingVerse = true
                }
            } else if (expectedVerseRange.size == 2) {
                for (i in expectedVerseRange[1] downTo expectedVerseRange[0]) {
                    if (!foundVerses.contains(i)) {
                        // generate missing verse
                        val verse: Span
                        if (verseListener == null) {
                            verse = USXVerseSpan(i)
                        } else {
                            verse = USXVersePinSpan(i)
                        }
                        verse.onClickListener = verseListener
                        out = TextUtils.concat(verse.toCharSequence(context), out)
                        addedMissingVerse = true
                    }
                }
            }
        }
        return out
    }

    /**
     * Renders all paragraph tags
     * @param input
     * @return
     */
    fun renderBrokenMarkers(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        out = removePattern(input, beginParagraphPattern)
        out = removePattern(out, endParagraphPattern)
        return out
    }

    /**
     * Renders all paragraph tags
     * @param input
     * @return
     */
    fun removePattern(input: CharSequence, pattern: Pattern): CharSequence {
        val matcher = pattern.matcher(input)
        var out: CharSequence = ""
        var lastIndex = 0
        while (matcher.find()) {
            if (isStopped()) return input

            out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()))
            lastIndex = matcher.end()
        }
        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Renders all paragraph tags
     * @param input
     * @return
     */
    fun renderParagraph(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = paraPattern("p")
        val matcher = pattern.matcher(input)
        var lastIndex = 0
        while (matcher.find()) {
            if (isStopped()) return input
            var lineBreak = ""
            if (matcher.start() > 0) {
                lineBreak = "\n"
            }
            out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), lineBreak, "    ", input.subSequence(matcher.start(1), matcher.end(1)), "\n")
            lastIndex = matcher.end()
        }
        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Renders all blank line tags
     * @param input
     * @return
     */
    fun renderBlankLine(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = paraShortPattern("b")
        val matcher = pattern.matcher(input)
        var lastIndex = 0
        while (matcher.find()) {
            if (isStopped()) return input
            out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), "\n\n")
            lastIndex = matcher.end()
        }
        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Renders a chapter label
     * @param input
     * @return
     */
    fun renderChapterLabel(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = paraPattern("cl")
        val matcher = pattern.matcher(input)
        var lastIndex = 0
        while (matcher.find()) {
            if (isStopped()) return input

            val span = SpannableString(input.subSequence(matcher.start(1), matcher.end(1)))
            span.setSpan(StyleSpan(Typeface.BOLD), 0, span.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)

            out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), span)
            lastIndex = matcher.end()
        }
        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Renders all poetic line tags
     * @param input
     * @return
     */
    fun renderPoeticLine(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = paraPattern("q(\\d+)")
        val matcher = pattern.matcher(input)
        var lastIndex = 0
        while (matcher.find()) {
            if (isStopped()) return input
            val level = Integer.parseInt(matcher.group(1)!!)
            val span = SpannableString(input.subSequence(matcher.start(2), matcher.end(2)))
            span.setSpan(StyleSpan(Typeface.NORMAL), 0, span.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
            var padding = ""
            for (i in 0 until level) {
                padding += "    "
            }

            // outdent for verse markers
            if (level > 0 && span.toString().indexOf("<verse number") == 0) {
                padding = padding.substring(0, padding.length - 2)
            }

            // don't stack new lines
            var leadingLineBreak = ""
            var trailingLineBreak = ""

            // leading
            val previous = input.subSequence(0, matcher.start()).toString().replace(" ", "")
            val lastLineBreak = previous.lastIndexOf("\n")
            if (lastLineBreak < previous.length - 1) {
                leadingLineBreak = "\n"
            }

            // trailing
            val next = input.subSequence(matcher.end(), input.length).toString().replace(" ", "")
            val nextLineBreak = next.indexOf("\n")
            val nextParagraph = next.indexOf("<para")
            if (nextLineBreak > 0 && nextParagraph > 0) {
                trailingLineBreak = "\n"
            }

            out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), leadingLineBreak, padding, span, trailingLineBreak)
            lastIndex = matcher.end()
        }
        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Renders all right-aligned poetic line tags
     * @param input
     * @return
     */
    fun renderRightAlignedPoeticLine(input: CharSequence): CharSequence {
        var out: CharSequence = ""
        val pattern = paraPattern("qr")
        val matcher = pattern.matcher(input)
        var lastIndex = 0

        while (matcher.find()) {
            if (isStopped()) return input
            val span = SpannableStringBuilder(matcher.group(1))
            span.setSpan(StyleSpan(Typeface.ITALIC), 0, span.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
            span.setSpan(AlignmentSpan.Standard(Layout.Alignment.ALIGN_OPPOSITE), 0, span.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
            out = TextUtils.concat(out, input.subSequence(lastIndex, matcher.start()), "\n", span)
            lastIndex = matcher.end()
        }

        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))
        return out
    }

    /**
     * Return the leading section heading, if any. Non-leading major section headings, and leading
     * headings of other types, are not included.
     *
     * @see <a href="http://digitalbiblelibrary.org/static/docs/usx/parastyles.html">...</a>
     * @param input The string to examine for a leading major section heading.
     * @return The leading major section heading; or the empty string if there is none.
     */
    override fun getLeadingMajorSectionHeading(input: CharSequence): CharSequence {
        val pattern = paraPattern("ms")
        val matcher = pattern.matcher(input)

        return if (matcher.find() && 0 == matcher.start()) {
            matcher.group(1) ?: ""
        } else {
            ""
        }
    }

    fun renderCharTags(input: CharSequence): CharSequence {
        var out: CharSequence = ""

        // Find and cache note tag positions first
        val notePattern = Pattern.compile(USXNoteSpan.PATTERN)
        val noteMatcher = notePattern.matcher(input)
        val notes = ArrayList<Pair<Int, Int>>()

        while (noteMatcher.find()) {
            if (isStopped()) return input
            notes.add(Pair.create(noteMatcher.start(), noteMatcher.end()))
        }

        val charPattern = Pattern.compile(USXChar.PATTERN)
        val charMatcher = charPattern.matcher(input)

        var lastIndex = 0
        while (charMatcher.find()) {
            if (isStopped()) return input

            // Check if this char is a note char, so we can ignore it and not process as a single char
            if (isCharInNote(charMatcher.start(), charMatcher.end(), notes)) {
                continue
            }

            out = TextUtils.concat(
                out,
                input.subSequence(lastIndex, charMatcher.start()),
                charMatcher.group(USXChar.CHAR_TEXT_GROUP)
            )
            lastIndex = charMatcher.end()
        }

        out = TextUtils.concat(out, input.subSequence(lastIndex, input.length))

        return out
    }

    private fun isCharInNote(start: Int, end: Int, notes: List<Pair<Int, Int>>): Boolean {
        for (note in notes) {
            if (start >= note.first && end <= note.second) {
                return true
            }
        }
        return false
    }

    /**
     * see if missing verse was added
     */
    override val isAddedMissingVerse: Boolean
        get() = addedMissingVerse

    companion object {
        var beginParagraphStyle: String = "<para\\s+style=\"\\w*\"\\s*>"
        var beginParagraphPattern: Pattern = Pattern.compile(beginParagraphStyle)
        var endParagraphStyle: String = "</para>"
        var endParagraphPattern: Pattern = Pattern.compile(endParagraphStyle)

        /**
         * Returns a pattern that matches a para tag pair e.g. <para style=""></para>
         * @param style a string or regular expression to identify the style
         * @return
         */
        private fun paraPattern(style: String): Pattern {
            return Pattern.compile(
                "<para\\s+style=\"$style\"\\s*>\\s*(((?!</para>).)*)</para>",
                Pattern.DOTALL
            )
        }

        /**
         * Returns a pattern that matches a single para tag e.g. <para style=""/>
         * @param style a string or regular expression to identify the style
         * @return
         */
        private fun paraShortPattern(style: String): Pattern {
            return Pattern.compile("<para\\s+style=\"$style\"\\s*/>", Pattern.DOTALL)
        }
    }
}